### ISSUE TITLE
Urllib3 2.2.1 is vulnerable, but required by this package

### ISSUE THREAD

**Issue by jvemmer-inpay** [cboin1996/requests-html#15]
The requirements.txt file contains `urllib3==2.2.1`, which is vulnerable. See [their changelog](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#222-2024-06-17)

**Comment by cboin1996** [comment]
Updated all requirements for the package to latest: https://github.com/cboin1996/requests-html/pull/17
